import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SafeEnviroment from '../components/feedback/safeEnviroment/safeEnviroment'
import Banner from '../components/banner/home/banner'
import NavHome from '../components/navigators/home/nav'
import 'bootstrap/dist/css/bootstrap.min.css';
import FooterApp from '../components/footer/footer'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavHome />
      <SafeEnviroment />
      <Banner title={'titulo'} subtitle={'subtitle'} />
      <FooterApp />
    </div>
  )
}

export default Home
