import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SafeEnviroment from '../components/feedback/safeEnviroment/safeEnviroment'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Pagina Inicial</h1>
      <hr />
      <SafeEnviroment />
    </div>
  )
}

export default Home
